[options]
addons_path = /mnt/addons_library
data_dir = /var/lib/odoo
proxy_mode = True

db_host = db
db_port = 5432
db_user = odoo
db_password = odoo

admin_passwd = $pbkdf2-sha512$600000$sfY.x/j/vzfGmDMmhFCq1Q$Ws0Nnxp/UpISq7TwnZDadam.n07TURaBy3zqq/52SyEMRTOFS6LzsmYNOOHV9mdXygZYx5vXfO4//ONwzWOpnA

